### ISSUE TITLE
Upgraded to 0.4.2 and cannot read files in ZipFS

### ISSUE THREAD

**Issue by atty303** [zen-fs/zip#5]
```ts
    const rootZip = await fetch(`https://pob-web-asset.atty303.ninja/versions/v2.42.0/root.zip`);
    await zenfs.configure({
      mounts: {
        "/root": {
          backend: Zip,
          data: await rootZip.arrayBuffer(),
          name: "root.zip",
        },
      },
    });

    console.log(await zenfs.promises.exists("/root/.image.tsv")); // --> false
    console.log(await zenfs.promises.exists("/root")); // --> false
    console.log(await zenfs.promises.exists("/")); // --> true
```

Such a simple file existence check will also fail.
After a bit of chasing, it appears that it is trying to statSync an entry for "/" and it is not in the ZipFS entry list.
It is likely that the difference is that we stopped using IndexFS.

**Comment by dr-vortex** [comment]
I'm sorry, I cleary broke some things during the overhaul. [v0.4.3](https://github.com/zen-fs/zip/releases/tag/v0.4.3) fixes this.

**Comment by dr-vortex** [comment]
@atty303 Does this fix all of the issues?

Again, I apologize for all of the bugs.
