### ISSUE TITLE
No export FileType for zip

### ISSUE THREAD

**Issue by dastanaron** [zen-fs/zip#8]
[ERROR] No matching export in "node_modules/@zenfs/core/dist/index.js" for import "FileType"
    node_modules/@zenfs/zip/dist/ZipFS.js:1:9:
      1 │ import { FileType, NoSyncFile, Stats, flagToMode, isWriteable } from '@zenfs/core';
      
      
Really no export

```js
//in zip/dist/zip.js
import { FileType, Stats } from '@zenfs/core/stats.js';
```

But in `@zenfs/core/stats.js` no export FileType

My versions:
    "@zenfs/core": "^0.16.2",
    "@zenfs/zip": "^0.4.5",

**Comment by dastanaron** [comment]
I install older version of `core` and this working
    "@zenfs/core": "0.15.2",
    "@zenfs/zip": "0.4.5",

**Comment by james-pre** [comment]
This is correct, `FileType` was changed from an enum to a type.

I'll publish a fix soon.

**Comment by james-pre** [comment]
@dastanaron,

The fix was commited in https://github.com/zen-fs/zip/commit/21afcb410b7a8dc5dee46ef7f15fa90ea12c7615 on July 25th, but was not actually published on NPM. [0.4.6](https://github.com/zen-fs/zip/releases/tag/v0.4.6) includes that commit.

**Comment by dastanaron** [comment]
@james-pre 
Yes, this problem has been solved. Than you so much!

Now, I fix this versions in my package.json:
    "@zenfs/core": "0.16.2",
    "@zenfs/zip": "0.4.6",
